# Generated by Django 3.1.3 on 2020-11-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0004_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('message_status', models.CharField(default='UNREAD', max_length=20)),
                ('date_sent', models.DateTimeField(max_length=20)),
            ],
        ),
    ]
