# Generated by Django 3.1.3 on 2020-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='NO SUBJECT', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_status',
            field=models.BooleanField(default=False),
        ),
    ]
