# Generated by Django 3.1.3 on 2020-11-14 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0006_auto_20201111_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tour.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
