# Generated by Django 3.1.3 on 2020-11-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0008_auto_20201116_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=500)),
                ('price', models.FloatField(max_length=20)),
                ('name', models.CharField(max_length=1000)),
                ('car_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_booked', models.DateTimeField(max_length=20)),
                ('rental_city', models.CharField(max_length=1000)),
                ('book_status', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(max_length=20)),
                ('instructions', models.TextField(max_length=1000)),
                ('car_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.car')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.profile')),
            ],
        ),
    ]
