# Generated by Django 3.1.3 on 2020-11-28 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tour', '0012_auto_20201128_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requestUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
