# Generated by Django 3.1.3 on 2020-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0015_booking_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_no',
            field=models.CharField(default=12345678, max_length=1000),
        ),
    ]
