# Generated by Django 3.1.3 on 2020-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0016_profile_passport_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_no',
            field=models.CharField(max_length=1000),
        ),
    ]
