# Generated by Django 3.1.3 on 2020-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0017_auto_20201202_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book_status',
            field=models.BooleanField(default=False),
        ),
    ]
