# Generated by Django 3.1.3 on 2020-12-02 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tour', '0018_profile_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_guide',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking_guide',
            name='touristguide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.profile'),
        ),
    ]
