# Generated by Django 3.1.3 on 2020-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0020_booking_guide_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_guide',
            name='if_read',
            field=models.BooleanField(default=False),
        ),
    ]
