# Generated by Django 3.1.3 on 2020-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0021_booking_guide_if_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_guide',
            name='guide_response',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'succesful'), (2, 'declined')], default=0),
        ),
    ]
