# Generated by Django 3.1.3 on 2020-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0025_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
