# Generated by Django 3.1.3 on 2020-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0026_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(max_length=500),
        ),
    ]
