# Generated by Django 3.1.3 on 2020-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0027_auto_20201212_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=500)),
                ('activity_image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=500)),
                ('activity_description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_image', models.ImageField(upload_to='images/')),
                ('event_location', models.CharField(max_length=500)),
                ('event_description', models.CharField(max_length=2000)),
            ],
        ),
    ]
