# Generated by Django 3.1.3 on 2020-12-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0028_activities_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activity_name',
            new_name='activityName',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='eventName',
        ),
    ]
