# Generated by Django 3.1.3 on 2020-12-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0029_auto_20201213_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
