# Generated by Django 3.1.3 on 2021-02-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0030_auto_20201213_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_guide',
            name='activities',
            field=models.ManyToManyField(blank=True, to='Tour.Activity'),
        ),
        migrations.AddField(
            model_name='booking_guide',
            name='events',
            field=models.ManyToManyField(blank=True, to='Tour.Event'),
        ),
        migrations.AddField(
            model_name='booking_guide',
            name='sites',
            field=models.ManyToManyField(blank=True, to='Tour.site'),
        ),
    ]
