# Generated by Django 3.1.3 on 2021-02-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0031_auto_20210213_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'All-Activitie'},
        ),
        migrations.AlterModelOptions(
            name='booking_guide',
            options={'verbose_name': 'Tourist Guide booking'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'All-Event'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Guide_Like'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User_Profile'},
        ),
        migrations.AlterModelOptions(
            name='publichat',
            options={'verbose_name': 'public-chat'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Attraction_site'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'New'},
        ),
    ]
