# Generated by Django 3.1.3 on 2021-03-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0034_auto_20210223_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_copy', models.FileField(default='document', upload_to='documents/')),
                ('application_time', models.DateTimeField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour.profile')),
            ],
            options={
                'verbose_name': 'Guide application',
                'verbose_name_plural': 'Guide applications',
            },
        ),
    ]
